version: 2
jobs:
  build:
    docker:
      - image: docker:17.07.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t miyajan/test-circleci-docker
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push miyajan/test-circleci-docker
