version: 2
jobs:
  docker-publish:
    docker:
      - image: docker:17.07.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t miyajan/test-circleci-docker:${CIRCLE_TAG} .
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push miyajan/test-circleci-docker:${CIRCLE_TAG}
workflows:
  version: 2
  build:
    jobs:
      - docker-publish:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
